version: '3.8'

services:
  app:
    build:
      context: ./ear
    image: ear:1.0
    ports:
      - 5000:5000
    volumes:
      - ./ear:/opt
    depends_on: [db]
  db:
    image: postgres:11.0
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
